[package]
name = "rust_power_panel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "power_panel"
path = "src/main.rs"

[features]
default = ["gui"]
gui = ["dep:gtk4", "dep:gtk4-layer-shell", "dep:glib"]

[dependencies]
gtk4             = { version = "0.11", features = ["v4_6"], optional = true }
gtk4-layer-shell = { version = "0.8", optional = true }
nvml-wrapper     = "0.12.1"
tokio            = { version = "1.0", features = ["full"] }
sysinfo          = "0.38"
glib             = { version = "0.20", optional = true }

[profile.release]
opt-level = 3        # Maksimum hız optimizasyonu
lto = true           # Link Time Optimization (Daha küçük ve hızlı binary)
strip = true         # Sembolleri silerek dosya boyutunu %80 küçültür
codegen-units = 1    # Derleme yavaşlar ama çalışma hızı artar
panic = "abort"      # Hata anında doğrudan kapanarak belleği hızlı boşaltır